# .github/workflows/ci-build.yml
name: 2roam v1.1 - Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build artefacts
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        project: [ core, frontend, backend ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        working-directory: ./${{ matrix.project }}
        run: npm ci

      - name: Build
        working-directory: ./${{ matrix.project }}
        run: npm run build

      - name: Upload build artefacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.project }}
          path: ./${{ matrix.project }}/dist
